name: Annotate problems

inputs:
  matcher-config-path:
    required: true
  analysis-report-path:
    required: true
  changed-files:
    required: false

runs:
  using: "composite"
  steps:
    - name: Add problem matcher
      run: echo "::add-matcher::$MATCHER_CONFIG_PATH"
      env:
        MATCHER_CONFIG_PATH: ${{ inputs.matcher-config-path }}
      shell: bash

    - name: Annotation problems
      run: |
        echo $CHANGED_FILES
        touch $GREP_RESULT_PATH
        for FILE in $CHANGED_FILES; do
          echo "$FILE"
          grep -1 -E ".*$FILE.*" $ANALYSIS_REPORT_PATH >> $GREP_RESULT_PATH || [[ $? == 1 ]]
        done
      env:
        CHANGED_FILES: ${{ inputs.changed-files }}
        ANALYSIS_REPORT_PATH: ${{ inputs.analysis-report-path }}
        GREP_RESULT_PATH: grep_result.txt
      shell: bash

    - name: Determin job status (Currently, even one annotation is judged to be an error.)
      run: |
        if [[ $(wc -l < "$GREP_RESULT_PATH") -gt 0 ]]; then exit 1; else exit 0; fi
        rm $GREP_RESULT_PATH
      env:
        GREP_RESULT_PATH: grep_result.txt;
      shell: bash

    - name: Remove problem matcher
      if: always()
      run: echo "::remove-matcher owner=analyzer::"
      shell: bash
