name: Annotate problems

inputs:
  matcher-config-path:
    required: true
  analysis-report-path:
    required: true
  changed-files:
    required: false

runs:
  using: "composite"
  steps:
    - name: Define env variables
      run: |
        echo "TMP_FILE_PATH=annotaion_problems_tmp.txt"  >> $GITHUB_ENV
      shell: bash

    - name: Add problem matcher
      run: echo "::add-matcher::$MATCHER_CONFIG_PATH"
      env:
        MATCHER_CONFIG_PATH: ${{ inputs.matcher-config-path }}
      shell: bash

    - name: Create tmp file
      run: touch ${{ env.TMP_FILE_PATH }}
      shell: bash

    - name: Annotation problems
      run: |
        echo $CHANGED_FILES
        for FILE in $CHANGED_FILES; do
          echo "$FILE"
          grep -E ".*$FILE.*" $ANALYSIS_REPORT_PATH >> ${{ env.TMP_FILE_PATH }} || [[ $? == 1 ]]
        done
      env:
        CHANGED_FILES: ${{ inputs.changed-files }}
        ANALYSIS_REPORT_PATH: ${{ inputs.analysis-report-path }}
      shell: bash

    - name: Annotate to codebase
      run: cat ${{ env.TMP_FILE_PATH }}
      shell: bash

    - name: Determin job status (Currently, even one annotation is judged to be an error.)
      run: if [[ $(wc -l < "${{ env.TMP_FILE_PATH }}") -gt 0 ]]; then exit 1; else exit 0; fi
      shell: bash

    - name: remove tmp file
      if: always()
      run: rm ${{ env.TMP_FILE_PATH }}
      shell: bash

    - name: Remove problem matcher
      if: always()
      run: echo "::remove-matcher owner=analyzer::"
      shell: bash
