name: Flutter CI

on:
  workflow_dispatch:
    inputs:
      flutter-version:
        required: true
        type: string
  workflow_call:
    inputs:
      flutter-version:
        required: true
        type: string

jobs:
  flutter-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ inputs.flutter-version }}
          channel: 'stable'
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter

      - name: Get flutter packages
        run: flutter pub get

      - name: Run unit test
        id: run-unit-test
        run: flutter test --coverage --coverage-path=./coverage/lcov.info --machine > flutter_test_report.txt

      - name: Report test result
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: 'flutter test'
          path: 'flutter_test_report.txt'
          reporter: 'flutter-json'
          fail-on-error: 'false'

      - name: Upload a coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info

      - name: Check lint
        id: check-lint
        continue-on-error: true
        if: steps.run-unit-test.outcome == 'success'
        run: flutter analyze > flutter_analyze_report.txt

      - name: Check code metrics
        id: check-code-metrics
        if: steps.run-unit-test.outcome == 'success'
        run: |
          flutter pub run dart_code_metrics:metrics analyze lib --reporter=console > dart-code-metrics_analyze_report.txt

      - name: Get changed files
        id: changed-files
        if: always()
        uses: solevin/action-library/.github/actions/get-chaged-files@main

      - name: Get config files
        if: always()
        uses: actions/checkout@v3
        with:
          repository: solevin/action-library
          ref: main
          path: ./solevin/action-library
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Annotation for lint checker
        if: always() && steps.check-lint.outcome != 'skipped'
        uses: ./solevin/action-library/.github/actions/annotate-problems
        with:
          matcher-config-path: ./solevin/action-library/.github/resources/analyzer-problem-matcher.json
          analysis-report-path: ./flutter_analyze_report.txt
          changed-files: ${{ steps.changed-files.outputs.changed-files }}

      - name: Annotation for DMC checker
        if: always() && steps.check-code-metrics.outcome != 'skipped'
        uses: ./solevin/action-library/.github/actions/annotate-problems
        with:
          matcher-config-path: ./solevin/action-library/.github/resources/analyzer-problem-matcher.json
          analysis-report-path: ./dart-code-metrics_analyze_report.txt
          changed-files: ${{ steps.changed-files.outputs.changed-files }}
